apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ksql-server
  name: ksql-server
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ksql-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ksql-server
    spec:
      containers:
      - env:
        - name: KSQL_LISTENERS
          value: http://0.0.0.0:8088
        - name: KSQL_BOOTSTRAP_SERVERS
          value: kafka-60046646:9092
        - name: KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE
          value: 'true'
        - name: KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE
          value: 'true'
        image: docker.io/confluentinc/cp-ksqldb-server:7.6.0
        imagePullPolicy: IfNotPresent
        name: ksql-server
        resources:
          limits:
            cpu: '2'
            ephemeral-storage: 5000Mi
            memory: 4000Mi
          requests:
            cpu: 100m
            ephemeral-storage: 100Mi
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ksql-server
  name: ksql-server
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: port-8088
    port: 8088
    protocol: TCP
    targetPort: 8088
  selector:
    app: ksql-server
  sessionAffinity: None
  type: ClusterIP

